### ISSUE TITLE
Question about CRDT Implementation

### ISSUE THREAD

**Issue by fnaith** [cachapa/crdt#8]
What kind of crdt this repository implement?
Does it support json type like [Automerge](https://github.com/automerge/hypermerge) ?

**Comment by cachapa** [comment]
I'm not sure what you mean by what kind of crdt.
The implementation follows closely what is described in the links in this project's readme.

It doesn't explicitly support Automerge out of the box. The crdt handles conflict resolution itself and even has helper methods to import/export json payloads.

**Comment by fnaith** [comment]
Thanks, I should study the links more.
